package com.vtradex.wms.webservice.client.sap.prdmove;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:58:04.515+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "https://wms.tcl.com/prd_move", name = "SI_Wms_Prd_Move_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWmsPrdMoveOB {

    @WebResult(name = "MM_Prd_Move_Resp", targetNamespace = "https://wms.tcl.com/prd_move", partName = "MM_Prd_Move_Resp")
    @WebMethod(operationName = "SI_Wms_Prd_Move_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWmsPrdMoveOB(
        @WebParam(partName = "MM_Prd_Move_Req", name = "MM_Prd_Move_Req", targetNamespace = "https://wms.tcl.com/prd_move")
        DTPrdMove mmPrdMoveReq
    );
}
