
package com.vtradex.wms.webservice.client.sap.othership;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:57:49.628+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsOtherMoveOB_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/other_move", "SI_Wms_Other_Move_OBService");

    private SIWmsOtherMoveOB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsOtherMoveOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsOtherMoveOBService ss = new SIWmsOtherMoveOBService(wsdlURL, SERVICE_NAME);
        SIWmsOtherMoveOB port = ss.getHTTPSPort();  
        
        {
        System.out.println("Invoking siWmsOtherMoveOB...");
        com.vtradex.wms.webservice.client.sap.othership.DTOtherMove _siWmsOtherMoveOB_mmOtherMoveReq = null;
        com.vtradex.wms.webservice.client.sap.othership.DTRetMsg _siWmsOtherMoveOB__return = port.siWmsOtherMoveOB(_siWmsOtherMoveOB_mmOtherMoveReq);
        System.out.println("siWmsOtherMoveOB.result=" + _siWmsOtherMoveOB__return);


        }

        System.exit(0);
    }

}
