package com.vtradex.wms.webservice.client.sap.othership;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:57:49.763+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SI_Wms_Other_Move_OBService", 
                  wsdlLocation = "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/other.wsdl",
                  targetNamespace = "http://wms.tcl.com/other_move") 
public class SIWmsOtherMoveOBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wms.tcl.com/other_move", "SI_Wms_Other_Move_OBService");
    public final static QName HTTPSPort = new QName("http://wms.tcl.com/other_move", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://wms.tcl.com/other_move", "HTTP_Port");
    static {
        URL url = SIWmsOtherMoveOBService.class.getResource("/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/other.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SIWmsOtherMoveOBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/other.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SIWmsOtherMoveOBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIWmsOtherMoveOBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWmsOtherMoveOBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SIWmsOtherMoveOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsOtherMoveOB getHTTPSPort() {
        return super.getPort(HTTPSPort, SIWmsOtherMoveOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsOtherMoveOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsOtherMoveOB getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIWmsOtherMoveOB.class, features);
    }
    /**
     *
     * @return
     *     returns SIWmsOtherMoveOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsOtherMoveOB getHTTPPort() {
        return super.getPort(HTTPPort, SIWmsOtherMoveOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsOtherMoveOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsOtherMoveOB getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIWmsOtherMoveOB.class, features);
    }

}
