package com.vtradex.wms.webservice.client.sap.supplier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-18T14:09:26.763+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/vendor_confirm", name = "SI_WMS_Confirm_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWMSConfirmOB {

    @WebResult(name = "MM_Confirm_Resp", targetNamespace = "http://wms.tcl.com/vendor_confirm", partName = "MM_Confirm_Resp")
    @WebMethod(operationName = "SI_WMS_Confirm_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWMSConfirmOB(
        @WebParam(partName = "MM_Confirm_Req", name = "MM_Confirm_Req", targetNamespace = "http://wms.tcl.com/vendor_confirm")
        DTVENConfirm mmConfirmReq
    );
}
