package com.vtradex.wms.webservice.client.sap.inv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-18T14:09:18.802+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/wms_stock", name = "SI_Wms_Stock_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWmsStockOB {

    @WebResult(name = "MM_STOCK_Resp", targetNamespace = "http://wms.tcl.com/wms_stock", partName = "MM_STOCK_Resp")
    @WebMethod(operationName = "SI_Wms_Stock_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWmsStockOB(
        @WebParam(partName = "MM_STOCK_Req", name = "MM_STOCK_Req", targetNamespace = "http://wms.tcl.com/wms_stock")
        DTSTOCK mmSTOCKReq
    );
}
