package com.vtradex.wms.webservice.client.sap.cancelreceive;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-24T17:46:57.779+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SI_Wms_Receipt_Undo_OBService", 
                  wsdlLocation = "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/cancelReceive.wsdl",
                  targetNamespace = "https://wms.tcl.com/Receipt_Undo") 
public class SIWmsReceiptUndoOBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://wms.tcl.com/Receipt_Undo", "SI_Wms_Receipt_Undo_OBService");
    public final static QName HTTPSPort = new QName("https://wms.tcl.com/Receipt_Undo", "HTTPS_Port");
    public final static QName HTTPPort = new QName("https://wms.tcl.com/Receipt_Undo", "HTTP_Port");
    static {
        URL url = SIWmsReceiptUndoOBService.class.getResource("/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/cancelReceive.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SIWmsReceiptUndoOBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/cancelReceive.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SIWmsReceiptUndoOBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIWmsReceiptUndoOBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWmsReceiptUndoOBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SIWmsReceiptUndoOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsReceiptUndoOB getHTTPSPort() {
        return super.getPort(HTTPSPort, SIWmsReceiptUndoOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsReceiptUndoOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsReceiptUndoOB getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIWmsReceiptUndoOB.class, features);
    }
    /**
     *
     * @return
     *     returns SIWmsReceiptUndoOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsReceiptUndoOB getHTTPPort() {
        return super.getPort(HTTPPort, SIWmsReceiptUndoOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsReceiptUndoOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsReceiptUndoOB getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIWmsReceiptUndoOB.class, features);
    }

}
