
package com.vtradex.wms.webservice.client.sap.saleoutdelivery;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:57:58.654+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIOutdeliveryPostOB_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/Outbound_Post", "SI_Outdelivery_Post_OBService");

    private SIOutdeliveryPostOB_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIOutdeliveryPostOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIOutdeliveryPostOBService ss = new SIOutdeliveryPostOBService(wsdlURL, SERVICE_NAME);
        SIOutdeliveryPostOB port = ss.getHTTPPort();  
        
        {
        System.out.println("Invoking siOutdeliveryPostOB...");
        com.vtradex.wms.webservice.client.sap.saleoutdelivery.DTODVPOST _siOutdeliveryPostOB_mmOutPostReq = null;
        com.vtradex.wms.webservice.client.sap.saleoutdelivery.DTRetMsg _siOutdeliveryPostOB__return = port.siOutdeliveryPostOB(_siOutdeliveryPostOB_mmOutPostReq);
        System.out.println("siOutdeliveryPostOB.result=" + _siOutdeliveryPostOB__return);


        }

        System.exit(0);
    }

}
