
package com.vtradex.wms.webservice.client.sap.resdata;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-03T10:14:08.234+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsResIssueOB_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/Res_Issue", "SI_Wms_Res_Issue_OBService");

    private SIWmsResIssueOB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsResIssueOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsResIssueOBService ss = new SIWmsResIssueOBService(wsdlURL, SERVICE_NAME);
        SIWmsResIssueOB port = ss.getHTTPSPort();  
        
        {
        System.out.println("Invoking siWmsResIssueOB...");
        com.vtradex.wms.webservice.client.sap.resdata.DTResIssue _siWmsResIssueOB_mmResIssueReq = null;
        com.vtradex.wms.webservice.client.sap.resdata.DTRetMsg _siWmsResIssueOB__return = port.siWmsResIssueOB(_siWmsResIssueOB_mmResIssueReq);
        System.out.println("siWmsResIssueOB.result=" + _siWmsResIssueOB__return);


        }

        System.exit(0);
    }

}
