SELECT 
 ITEM.CODE AS "库存数据集.货品代码",
 SUM(INV.QTY) AS "库存数据集.可用数量"
 FROM WMS_INVENTORY INV
 LEFT JOIN WMS_ITEM_KEY ITEM_KEY ON ITEM_KEY.ID = INV.ITEM_KEY_ID
 LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = ITEM_KEY.ITEM_ID
 LEFT JOIN WMS_LOCATION LOC ON LOC.ID = INV.LOCATION_ID
 LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOC.ZONE_ID
 LEFT JOIN WMS_PACKAGE_UNIT UNIT ON UNIT.ID = INV.PACKAGE_UNIT_ID
WHERE 1=1
 AND INV.OPERATION_STATUS IN ('NORMAL','READY_IN') 
 AND LOC.TYPE = 'STORAGE'
 AND INV.QTY > 0
 /~仓库ID: AND LOC.WAREHOUSE_ID = {仓库ID}~/
 /~拣货库位定位分类: AND LOC.PUTAWAY_CATEGORY = {拣货库位定位分类}~/
 /~货品ID: AND ITEM.ID = {货品ID}~/
 GROUP BY ITEM.CODE