package com.vtradex.wms.webservice.client.sap.othership;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:57:49.752+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/other_move", name = "SI_Wms_Other_Move_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWmsOtherMoveOB {

    @WebResult(name = "MM_Other_Move_Resp", targetNamespace = "http://wms.tcl.com/other_move", partName = "MM_Other_Move_Resp")
    @WebMethod(operationName = "SI_Wms_Other_Move_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWmsOtherMoveOB(
        @WebParam(partName = "MM_Other_Move_Req", name = "MM_Other_Move_Req", targetNamespace = "http://wms.tcl.com/other_move")
        DTOtherMove mmOtherMoveReq
    );
}
