SELECT
        LOCATION.ID AS "库位.库位ID",
        LOCATION.CODE AS "库位.库位编码",
        AREA.CODE AS "库位.库区编码",
        LOCATION.SEGMENT_NO AS "库位.块",
        LOCATION.LINE_NO AS "库位.排",
        LOCATION.COLUMN_NO AS "库位.列",
        LOCATION.LAYER_NO AS "库位.层",
        LOCATION.PUTAWAY_SEQUENCE AS "库位.上架动线号",
        LOCATION.USE_RATE AS "库位.库满度",
        LOCATION.MIX_RULE AS "库位.混放类型",
        CAPACITY.PALLET_QTY AS "库位.承载托数",
        CAPACITY.QTY_LIMIT AS "库位.承载数量",
        CAPACITY.WEIGHT_LIMIT AS "库位.承载重量",
        CAPACITY.VOLUME_LIMIT AS "库位.承载体积"
FROM WMS_TASK T 
LEFT JOIN WMS_LOCATION LOCATION ON LOCATION.ID = T.TO_LOCATION_ID
LEFT JOIN WMS_ZONE AREA ON AREA.ID = LOCATION.ZONE_ID
LEFT JOIN WMS_LOCATION_CAPACITY CAPACITY ON CAPACITY.ID = LOCATION.LOCATION_CAPACITY_ID
LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = T.ITEM_ID
WHERE 1=1
AND T.TYPE ='PUTAWAY'
AND T.STATUS IN  ('FINISH')
/~仓库ID: AND LOCATION.WAREHOUSE_ID = {仓库ID}~/
/~货品ID:  AND ITEM.ID =  {货品ID}~/
AND ROWNUM<=1
ORDER BY T.UPDATE_TIME DESC