package com.vtradex.wms.webservice.client.sap.delivery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-14T14:30:32.086+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SI_WMS_INBOUND_DLV_OBService", 
                  wsdlLocation = "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/sap_wms2sapdelivery.wsdl",
                  targetNamespace = "http://wms.tcl.com/inbound_delivery") 
public class SIWMSINBOUNDDLVOBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wms.tcl.com/inbound_delivery", "SI_WMS_INBOUND_DLV_OBService");
    public final static QName HTTPSPort = new QName("http://wms.tcl.com/inbound_delivery", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://wms.tcl.com/inbound_delivery", "HTTP_Port");
    static {
        URL url = SIWMSINBOUNDDLVOBService.class.getResource("/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/sap_wms2sapdelivery.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SIWMSINBOUNDDLVOBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/sap_wms2sapdelivery.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SIWMSINBOUNDDLVOBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIWMSINBOUNDDLVOBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWMSINBOUNDDLVOBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SIWMSINBOUNDDLVOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWMSINBOUNDDLVOB getHTTPSPort() {
        return super.getPort(HTTPSPort, SIWMSINBOUNDDLVOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWMSINBOUNDDLVOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWMSINBOUNDDLVOB getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIWMSINBOUNDDLVOB.class, features);
    }
    /**
     *
     * @return
     *     returns SIWMSINBOUNDDLVOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWMSINBOUNDDLVOB getHTTPPort() {
        return super.getPort(HTTPPort, SIWMSINBOUNDDLVOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWMSINBOUNDDLVOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWMSINBOUNDDLVOB getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIWMSINBOUNDDLVOB.class, features);
    }

}
