package com.vtradex.wms.webservice.client.sap.item;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-18T14:09:23.198+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SI_Wms_Mat_Attr_OBService", 
                  wsdlLocation = "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/wmsItem2sap.wsdl",
                  targetNamespace = "http://wms.tcl.com/material_attr") 
public class SIWmsMatAttrOBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wms.tcl.com/material_attr", "SI_Wms_Mat_Attr_OBService");
    public final static QName HTTPSPort = new QName("http://wms.tcl.com/material_attr", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://wms.tcl.com/material_attr", "HTTP_Port");
    static {
        URL url = SIWmsMatAttrOBService.class.getResource("/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/wmsItem2sap.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SIWmsMatAttrOBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/wmsItem2sap.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SIWmsMatAttrOBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIWmsMatAttrOBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWmsMatAttrOBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SIWmsMatAttrOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsMatAttrOB getHTTPSPort() {
        return super.getPort(HTTPSPort, SIWmsMatAttrOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsMatAttrOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsMatAttrOB getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIWmsMatAttrOB.class, features);
    }
    /**
     *
     * @return
     *     returns SIWmsMatAttrOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsMatAttrOB getHTTPPort() {
        return super.getPort(HTTPPort, SIWmsMatAttrOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsMatAttrOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsMatAttrOB getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIWmsMatAttrOB.class, features);
    }

}
