package com.vtradex.wms.webservice.client.sap.item;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-18T14:09:23.175+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/material_attr", name = "SI_Wms_Mat_Attr_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWmsMatAttrOB {

    @WebResult(name = "MM_Mat_Attr_Resp", targetNamespace = "http://wms.tcl.com/material_attr", partName = "MM_Mat_Attr_Resp")
    @WebMethod(operationName = "SI_Wms_Mat_Attr_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWmsMatAttrOB(
        @WebParam(partName = "MM_Mat_Attr_Req", name = "MM_Mat_Attr_Req", targetNamespace = "http://wms.tcl.com/material_attr")
        DTMatAttr mmMatAttrReq
    );
}
