package com.vtradex.wms.webservice.client.sap.resdata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-03T10:14:08.409+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/Res_Issue", name = "SI_Wms_Res_Issue_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWmsResIssueOB {

    @WebResult(name = "MM_Res_Issue_Resp", targetNamespace = "http://wms.tcl.com/Res_Issue", partName = "MM_Res_Issue_Resp")
    @WebMethod(operationName = "SI_Wms_Res_Issue_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWmsResIssueOB(
        @WebParam(partName = "MM_Res_Issue_Req", name = "MM_Res_Issue_Req", targetNamespace = "http://wms.tcl.com/Res_Issue")
        DTResIssue mmResIssueReq
    );
}
