
package com.vtradex.wms.webservice.client.sap.bfck;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:57:53.735+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsScrapOutOB_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/Scrap_Out", "SI_Wms_Scrap_Out_OBService");

    private SIWmsScrapOutOB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsScrapOutOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsScrapOutOBService ss = new SIWmsScrapOutOBService(wsdlURL, SERVICE_NAME);
        SIWmsScrapOutOB port = ss.getHTTPSPort();  
        
        {
        System.out.println("Invoking siWmsScrapOutOB...");
        com.vtradex.wms.webservice.client.sap.bfck.DTScrapOut _siWmsScrapOutOB_mmScrapOutReq = null;
        com.vtradex.wms.webservice.client.sap.bfck.DTRetMsg _siWmsScrapOutOB__return = port.siWmsScrapOutOB(_siWmsScrapOutOB_mmScrapOutReq);
        System.out.println("siWmsScrapOutOB.result=" + _siWmsScrapOutOB__return);


        }

        System.exit(0);
    }

}
