package com.vtradex.wms.webservice.client.sap.bfck;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:57:53.849+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/Scrap_Out", name = "SI_Wms_Scrap_Out_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWmsScrapOutOB {

    @WebResult(name = "MM_Scrap_Out_Resp", targetNamespace = "http://wms.tcl.com/Scrap_Out", partName = "MM_Scrap_Out_Resp")
    @WebMethod(operationName = "SI_Wms_Scrap_Out_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWmsScrapOutOB(
        @WebParam(partName = "MM_Scrap_Out_Req", name = "MM_Scrap_Out_Req", targetNamespace = "http://wms.tcl.com/Scrap_Out")
        DTScrapOut mmScrapOutReq
    );
}
