
package com.vtradex.wms.webservice.client.sap.cancelreceive;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-24T17:46:57.673+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsReceiptUndoOB_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("https://wms.tcl.com/Receipt_Undo", "SI_Wms_Receipt_Undo_OBService");

    private SIWmsReceiptUndoOB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsReceiptUndoOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsReceiptUndoOBService ss = new SIWmsReceiptUndoOBService(wsdlURL, SERVICE_NAME);
        SIWmsReceiptUndoOB port = ss.getHTTPSPort();  
        
        {
        System.out.println("Invoking siWmsReceiptUndoOB...");
        com.vtradex.wms.webservice.client.sap.cancelreceive.DTReceiptUndo _siWmsReceiptUndoOB_mmReceiptUndoReq = null;
        com.vtradex.wms.webservice.client.sap.cancelreceive.DTRetMsg _siWmsReceiptUndoOB__return = port.siWmsReceiptUndoOB(_siWmsReceiptUndoOB_mmReceiptUndoReq);
        System.out.println("siWmsReceiptUndoOB.result=" + _siWmsReceiptUndoOB__return);


        }

        System.exit(0);
    }

}
