
package com.vtradex.wms.webservice.client.sap.item;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-18T14:09:23.153+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsMatAttrOB_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/material_attr", "SI_Wms_Mat_Attr_OBService");

    private SIWmsMatAttrOB_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsMatAttrOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsMatAttrOBService ss = new SIWmsMatAttrOBService(wsdlURL, SERVICE_NAME);
        SIWmsMatAttrOB port = ss.getHTTPPort();  
        
        {
        System.out.println("Invoking siWmsMatAttrOB...");
        com.vtradex.wms.webservice.client.sap.item.DTMatAttr _siWmsMatAttrOB_mmMatAttrReq = null;
        com.vtradex.wms.webservice.client.sap.item.DTRetMsg _siWmsMatAttrOB__return = port.siWmsMatAttrOB(_siWmsMatAttrOB_mmMatAttrReq);
        System.out.println("siWmsMatAttrOB.result=" + _siWmsMatAttrOB__return);


        }

        System.exit(0);
    }

}
