
package com.vtradex.wms.webservice.client.sap.prdmove;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:58:04.404+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsPrdMoveOB_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("https://wms.tcl.com/prd_move", "SI_Wms_Prd_Move_OBService");

    private SIWmsPrdMoveOB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsPrdMoveOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsPrdMoveOBService ss = new SIWmsPrdMoveOBService(wsdlURL, SERVICE_NAME);
        SIWmsPrdMoveOB port = ss.getHTTPSPort();  
        
        {
        System.out.println("Invoking siWmsPrdMoveOB...");
        com.vtradex.wms.webservice.client.sap.prdmove.DTPrdMove _siWmsPrdMoveOB_mmPrdMoveReq = null;
        com.vtradex.wms.webservice.client.sap.prdmove.DTRetMsg _siWmsPrdMoveOB__return = port.siWmsPrdMoveOB(_siWmsPrdMoveOB_mmPrdMoveReq);
        System.out.println("siWmsPrdMoveOB.result=" + _siWmsPrdMoveOB__return);


        }

        System.exit(0);
    }

}
