package com.vtradex.wms.webservice.client.sap.returnback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-24T17:47:01.341+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/Receipt_Return", name = "SI_Wms_Receipt_Return_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIWmsReceiptReturnOB {

    @WebResult(name = "MM_Receipt_Return_Resp", targetNamespace = "http://wms.tcl.com/Receipt_Return", partName = "MM_Receipt_Return_Resp")
    @WebMethod(operationName = "SI_Wms_Receipt_Return_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siWmsReceiptReturnOB(
        @WebParam(partName = "MM_Receipt_Return_Req", name = "MM_Receipt_Return_Req", targetNamespace = "http://wms.tcl.com/Receipt_Return")
        DTReceiptReturn mmReceiptReturnReq
    );
}
