package com.vtradex.wms.webservice.client.sap.commcallback;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-04T12:04:31.029+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ZRFC_WMS_MSG_RETURNService", 
                  wsdlLocation = "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/sap_commcallback.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:rfc:functions") 
public class ZRFCWMSMSGRETURNService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:rfc:functions", "ZRFC_WMS_MSG_RETURNService");
    public final static QName HTTPSPort = new QName("urn:sap-com:document:sap:rfc:functions", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn:sap-com:document:sap:rfc:functions", "HTTP_Port");
    static {
        URL url = ZRFCWMSMSGRETURNService.class.getResource("/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/sap_commcallback.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZRFCWMSMSGRETURNService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/sap_commcallback.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ZRFCWMSMSGRETURNService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZRFCWMSMSGRETURNService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZRFCWMSMSGRETURNService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ZRFCWMSMSGRETURNPortType
     */
    @WebEndpoint(name = "HTTPS_Port")
    public ZRFCWMSMSGRETURNPortType getHTTPSPort() {
        return super.getPort(HTTPSPort, ZRFCWMSMSGRETURNPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZRFCWMSMSGRETURNPortType
     */
    @WebEndpoint(name = "HTTPS_Port")
    public ZRFCWMSMSGRETURNPortType getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, ZRFCWMSMSGRETURNPortType.class, features);
    }
    /**
     *
     * @return
     *     returns ZRFCWMSMSGRETURNPortType
     */
    @WebEndpoint(name = "HTTP_Port")
    public ZRFCWMSMSGRETURNPortType getHTTPPort() {
        return super.getPort(HTTPPort, ZRFCWMSMSGRETURNPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZRFCWMSMSGRETURNPortType
     */
    @WebEndpoint(name = "HTTP_Port")
    public ZRFCWMSMSGRETURNPortType getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, ZRFCWMSMSGRETURNPortType.class, features);
    }

}
