SELECT
pickTicket.ID AS "序号",
pickTicket.CODE AS "代码",
WMS_BILL_TYPE.NAME AS "单据类型",
COMPANY.NAME AS "货主",
CARRIER.NAME AS "承运商",
detail.ID AS "明细.序号",
detail.LINE_NO AS "明细.行号",
ITEM.ID AS "明细.货品序号",
ITEM.CODE AS "明细.货品代码",
ITEM.NAME AS "明细.货品名称",
ITEM.CLASS_1 AS "明细.货品分类",
PACKAGE_UNIT.CONVERT_FIGURE AS "明细.折算系数",
PACKAGE_UNIT.UNIT AS "明细.包装单位",
detail.EXPECTED_PACK_QTY AS "明细.包装数量",
detail.EXPECTED_QTY AS "明细.数量"
FROM WMS_PICK_TICKET pickTicket
LEFT JOIN WMS_BILL_TYPE WMS_BILL_TYPE ON WMS_BILL_TYPE.ID = pickTicket.BILL_TYPE_ID
LEFT JOIN WMS_COMPANY COMPANY ON COMPANY.ID = pickTicket.COMPANY_ID
LEFT JOIN WMS_CARRIER CARRIER ON CARRIER.ID = pickTicket.CARRIER_ID
LEFT JOIN WMS_PICK_TICKET_DETAIL detail ON detail.PICK_TICKET_ID = pickTicket.ID
LEFT JOIN WMS_PACKAGE_UNIT PACKAGE_UNIT ON PACKAGE_UNIT.ID = detail.PACKAGE_UNIT_ID
LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = detail.ITEM_ID
WHERE 1=1
/~拣货单序号: AND pickTicket.ID = {拣货单序号}~/
