
package com.vtradex.wms.webservice.client.sap.invmove;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-09T15:54:32.707+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsStockMoveOB_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("https://wms.tcl.com/stock_move", "SI_Wms_Stock_Move_OBService");

    private SIWmsStockMoveOB_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsStockMoveOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsStockMoveOBService ss = new SIWmsStockMoveOBService(wsdlURL, SERVICE_NAME);
        SIWmsStockMoveOB port = ss.getHTTPPort();  
        
        {
        System.out.println("Invoking siWmsStockMoveOB...");
        com.vtradex.wms.webservice.client.sap.invmove.DTStockMove _siWmsStockMoveOB_mmStockMoveReq = null;
        com.vtradex.wms.webservice.client.sap.invmove.DTRetMsg _siWmsStockMoveOB__return = port.siWmsStockMoveOB(_siWmsStockMoveOB_mmStockMoveReq);
        System.out.println("siWmsStockMoveOB.result=" + _siWmsStockMoveOB__return);


        }

        System.exit(0);
    }

}
