package com.vtradex.wms.webservice.client.sap.returnback;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-24T17:47:01.350+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SI_Wms_Receipt_Return_OBService", 
                  wsdlLocation = "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/returnBack.wsdl",
                  targetNamespace = "http://wms.tcl.com/Receipt_Return") 
public class SIWmsReceiptReturnOBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wms.tcl.com/Receipt_Return", "SI_Wms_Receipt_Return_OBService");
    public final static QName HTTPSPort = new QName("http://wms.tcl.com/Receipt_Return", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://wms.tcl.com/Receipt_Return", "HTTP_Port");
    static {
        URL url = SIWmsReceiptReturnOBService.class.getResource("/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/returnBack.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SIWmsReceiptReturnOBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/returnBack.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SIWmsReceiptReturnOBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIWmsReceiptReturnOBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWmsReceiptReturnOBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SIWmsReceiptReturnOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsReceiptReturnOB getHTTPSPort() {
        return super.getPort(HTTPSPort, SIWmsReceiptReturnOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsReceiptReturnOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWmsReceiptReturnOB getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIWmsReceiptReturnOB.class, features);
    }
    /**
     *
     * @return
     *     returns SIWmsReceiptReturnOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsReceiptReturnOB getHTTPPort() {
        return super.getPort(HTTPPort, SIWmsReceiptReturnOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWmsReceiptReturnOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWmsReceiptReturnOB getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIWmsReceiptReturnOB.class, features);
    }

}
