
package com.vtradex.wms.webservice.client.sap.returnback;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-24T17:47:01.323+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsReceiptReturnOB_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/Receipt_Return", "SI_Wms_Receipt_Return_OBService");

    private SIWmsReceiptReturnOB_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsReceiptReturnOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsReceiptReturnOBService ss = new SIWmsReceiptReturnOBService(wsdlURL, SERVICE_NAME);
        SIWmsReceiptReturnOB port = ss.getHTTPPort();  
        
        {
        System.out.println("Invoking siWmsReceiptReturnOB...");
        com.vtradex.wms.webservice.client.sap.returnback.DTReceiptReturn _siWmsReceiptReturnOB_mmReceiptReturnReq = null;
        com.vtradex.wms.webservice.client.sap.returnback.DTRetMsg _siWmsReceiptReturnOB__return = port.siWmsReceiptReturnOB(_siWmsReceiptReturnOB_mmReceiptReturnReq);
        System.out.println("siWmsReceiptReturnOB.result=" + _siWmsReceiptReturnOB__return);


        }

        System.exit(0);
    }

}
