
package com.vtradex.wms.webservice.client.sap.inv;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-18T14:09:18.776+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsStockOB_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/wms_stock", "SI_Wms_Stock_OBService");

    private SIWmsStockOB_HTTPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsStockOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsStockOBService ss = new SIWmsStockOBService(wsdlURL, SERVICE_NAME);
        SIWmsStockOB port = ss.getHTTPPort();  
        
        {
        System.out.println("Invoking siWmsStockOB...");
        com.vtradex.wms.webservice.client.sap.inv.DTSTOCK _siWmsStockOB_mmSTOCKReq = null;
        com.vtradex.wms.webservice.client.sap.inv.DTRetMsg _siWmsStockOB__return = port.siWmsStockOB(_siWmsStockOB_mmSTOCKReq);
        System.out.println("siWmsStockOB.result=" + _siWmsStockOB__return);


        }

        System.exit(0);
    }

}
