
package com.vtradex.wms.webservice.client.sap.receiveinfo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-09-07T11:31:33.225+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class SIWmsIndPostOB_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://wms.tcl.com/indelivery_Post", "SI_Wms_Ind_Post_OBService");

    private SIWmsIndPostOB_HTTPSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SIWmsIndPostOBService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SIWmsIndPostOBService ss = new SIWmsIndPostOBService(wsdlURL, SERVICE_NAME);
        SIWmsIndPostOB port = ss.getHTTPSPort();  
        
        {
        System.out.println("Invoking siWmsIndPostOB...");
        com.vtradex.wms.webservice.client.sap.receiveinfo.DTINDPOST _siWmsIndPostOB_mmIndPostReq = null;
        com.vtradex.wms.webservice.client.sap.receiveinfo.DTRetMsg _siWmsIndPostOB__return = port.siWmsIndPostOB(_siWmsIndPostOB_mmIndPostReq);
        System.out.println("siWmsIndPostOB.result=" + _siWmsIndPostOB__return);


        }

        System.exit(0);
    }

}
