package com.vtradex.wms.webservice.client.sap.saleoutdelivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-08-02T16:57:58.673+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://wms.tcl.com/Outbound_Post", name = "SI_Outdelivery_Post_OB")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIOutdeliveryPostOB {

    @WebResult(name = "MM_Out_Post_Resp", targetNamespace = "http://wms.tcl.com/Outbound_Post", partName = "MM_Out_Post_Resp")
    @WebMethod(operationName = "SI_Outdelivery_Post_OB", action = "http://sap.com/xi/WebService/soap1.1")
    public DTRetMsg siOutdeliveryPostOB(
        @WebParam(partName = "MM_Out_Post_Req", name = "MM_Out_Post_Req", targetNamespace = "http://wms.tcl.com/Outbound_Post")
        DTODVPOST mmOutPostReq
    );
}
