package com.vtradex.wms.webservice.client.sap.supplier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2017-07-18T14:09:26.790+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SI_WMS_Confirm_OBService", 
                  wsdlLocation = "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/wmsSupplierConfirm.wsdl",
                  targetNamespace = "http://wms.tcl.com/vendor_confirm") 
public class SIWMSConfirmOBService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wms.tcl.com/vendor_confirm", "SI_WMS_Confirm_OBService");
    public final static QName HTTPSPort = new QName("http://wms.tcl.com/vendor_confirm", "HTTPS_Port");
    public final static QName HTTPPort = new QName("http://wms.tcl.com/vendor_confirm", "HTTP_Port");
    static {
        URL url = SIWMSConfirmOBService.class.getResource("/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/wmsSupplierConfirm.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SIWMSConfirmOBService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/administrator/workspace/tcl_wms/src/main/resources/wsdl/wmsSupplierConfirm.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SIWMSConfirmOBService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIWMSConfirmOBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIWMSConfirmOBService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SIWMSConfirmOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWMSConfirmOB getHTTPSPort() {
        return super.getPort(HTTPSPort, SIWMSConfirmOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWMSConfirmOB
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIWMSConfirmOB getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIWMSConfirmOB.class, features);
    }
    /**
     *
     * @return
     *     returns SIWMSConfirmOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWMSConfirmOB getHTTPPort() {
        return super.getPort(HTTPPort, SIWMSConfirmOB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIWMSConfirmOB
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIWMSConfirmOB getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIWMSConfirmOB.class, features);
    }

}
