SELECT
WMSSO.ID AS "序号",
WMSSO.CODE AS "代码",
WMS_BILL_TYPE.NAME AS "单据类型",
COMPANY.NAME AS "货主",
CARRIER.NAME AS "承运商",
SO_DETAIL.ID AS "明细.序号",
SO_DETAIL.LINE_NO AS "明细.行号",
ITEM.ID AS "明细.货品序号",
ITEM.CODE AS "明细.货品代码",
ITEM.NAME AS "明细.货品名称",
ITEM.CLASS_1 AS "明细.货品分类",
PACKAGE_UNIT.CONVERT_FIGURE AS "明细.折算系数",
PACKAGE_UNIT.UNIT AS "明细.包装单位",
SO_DETAIL.EXPECTED_PACK_QTY AS "明细.包装数量",
SO_DETAIL.EXPECTED_QTY AS "明细.数量"
FROM WMS_SO WMSSO
LEFT JOIN WMS_BILL_TYPE WMS_BILL_TYPE ON WMS_BILL_TYPE.ID = WMSSO.BILL_TYPE_ID
LEFT JOIN WMS_COMPANY COMPANY ON COMPANY.ID = WMSSO.COMPANY_ID
LEFT JOIN WMS_CARRIER CARRIER ON CARRIER.ID = WMSSO.CARRIER_ID
LEFT JOIN WMS_SO_DETAIL SO_DETAIL ON SO_DETAIL.SO_ID = WMSSO.ID
LEFT JOIN WMS_PACKAGE_UNIT PACKAGE_UNIT ON PACKAGE_UNIT.ID = SO_DETAIL.PACKAGE_UNIT_ID
LEFT JOIN WMS_ITEM ITEM ON ITEM.ID = SO_DETAIL.ITEM_ID
WHERE 1=1
/~出库单序号: AND WMSSO.ID = {出库单序号}~/
